### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by botic** [robi42/ringo-mail#9]
I'm working on a fork with an updated javax.mail dependency and which should be published in packages.ringojs.org. But what's the actual license of the code? 🤔

**Comment by robi42** [comment]
Hi, thanks for pointing that out, and sorry for missing license info so far. 
Consequently, added an `MIT` license file in [LICENSE.txt](https://github.com/robi42/ringo-mail/commit/0437370). 
So, please feel free to use the code in any way you'd like.

**Comment by botic** [comment]
thx! I wanted to ask you directly at the meetup today, but your profile picture made it hard to identify you in the short break ;)

**Comment by robi42** [comment]
NP, could update that old mangatar profile pic, I suppose. :)
